// Development-only browser integration runner. Not included in the extension build.
const report:{passed:string[];failed:string[];errors:string[];exports:{name:string;bytes:number}[];finished?:string}={passed:[],failed:[],errors:[],exports:[]};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(fn:()=>any,message:string,timeout=20000){const start=performance.now();while(!fn()){if(performance.now()-start>timeout)throw new Error(message);await wait(100);}await wait(150);}
const assert=(value:any,message:string)=>{if(!value)throw new Error(message);};
const buttons=(label:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('button')).filter(b=>b.getAttribute('aria-label')===label||b.title===label||b.textContent?.trim()===label);
async function click(label:string){const b=buttons(label).find(b=>b.getClientRects().length&&!b.disabled);assert(b,`Button missing: ${label}`);b!.click();await wait(200);}
const text=(el:HTMLInputElement|HTMLTextAreaElement,value:string)=>{Object.getOwnPropertyDescriptor(el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));};
const blur=(el:HTMLElement)=>{el.dispatchEvent(new FocusEvent('focusout',{bubbles:true}));};
const idle=()=>until(()=>!document.querySelector('.busy'),'Busy operation did not finish');
const note=(name:string)=>report.passed.push(name);
window.addEventListener('error',e=>report.errors.push(e.message));window.addEventListener('unhandledrejection',e=>report.errors.push(String(e.reason)));
const anchorClick=HTMLAnchorElement.prototype.click;
HTMLAnchorElement.prototype.click=function(){if(this.download&&this.href.startsWith('blob:')){fetch(this.href).then(r=>r.arrayBuffer()).then(b=>report.exports.push({name:this.download,bytes:b.byteLength}));}else anchorClick.call(this);};
async function draw(x1:number,y1:number,x2:number,y2:number){const page=document.querySelector<HTMLElement>('.document-scroll .pdf-page')!;const rect=page.getBoundingClientRect(),scale=rect.width/595;const capture=page.setPointerCapture;page.setPointerCapture=()=>{};const fire=(type:string,x:number,y:number)=>page.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:1,pointerType:'mouse',button:0,buttons:type==='pointerup'?0:1,clientX:rect.left+x*scale,clientY:rect.top+y*scale,pressure:.5}));fire('pointerdown',x1,y1);await wait(60);fire('pointermove',x2,y2);await wait(60);fire('pointerup',x2,y2);page.setPointerCapture=capture;await idle();}
try{
 await until(()=>document.querySelector('.home'),'Home did not render');
 const sample=await (await fetch('/test-artifacts/sample.pdf')).arrayBuffer();const file=new File([sample],'QA sample.pdf',{type:'application/pdf'});const transfer=new DataTransfer();transfer.items.add(file);const input=document.querySelector<HTMLInputElement>('input[type=file]')!;input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));
 await wait(1500);if(buttons('Open original copy').length)await click('Open original copy');
 await until(()=>document.querySelector('.document-scroll canvas')?.getAttribute('width')!=='1'&&!!document.querySelector('.document-scroll canvas'),'PDF rendering failed');await idle();
 assert(!document.querySelector('.page-error'),'Page render error');assert(document.querySelectorAll('.document-scroll .text-layer span').length>20,'No selectable text');note('Local import, MuPDF worker rendering and selectable text');
 await click('Laser pointer');const laser=document.querySelector<HTMLElement>('.document-scroll .laser-overlay')!;assert(laser,'Laser overlay missing');const laserRect=laser.getBoundingClientRect();laser.setPointerCapture=()=>{};
 const fireLaser=(type:string,x:number)=>laser.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:23,pointerType:'mouse',button:type==='pointermove'?-1:0,buttons:type==='pointerup'?0:1,clientX:laserRect.left+x,clientY:laserRect.top+140}));
 fireLaser('pointerdown',60);fireLaser('pointermove',220);await until(()=>!!laser.querySelector('line')&&!!laser.querySelector('.laser-dot'),'Laser dot/trail did not appear');fireLaser('pointerup',220);await until(()=>!laser.querySelector('line'),'Laser trail did not fade',3000);assert(buttons('Undo')[0].disabled,'Laser created a PDF edit');
 await click('Select');assert(!document.querySelector('.laser-overlay'),'Laser did not clear when changing tools');assert(!document.querySelector('.mark-hit'),'Laser created a permanent annotation');note('Temporary laser dot and fading trail leave PDF and undo history unchanged');
 await click('Annotate');await click('Rectangle');await draw(60,350,180,430);assert(document.querySelectorAll('.mark-hit').length===0,'Drawing mode should not expose drag handles');await click('Select');assert(document.querySelectorAll('.mark-hit').length>=1,'Rectangle was not created');note('Annotation placement through canvas pointer events');
 await click('Undo');assert(document.querySelectorAll('.mark-hit').length===0,'Undo did not remove annotation');await click('Redo');assert(document.querySelectorAll('.mark-hit').length>=1,'Redo did not restore annotation');note('UI undo and redo');
 await click('Pen');for(const x of [100,200,300])await draw(x,500,x,550);await click('Eraser');
 const erasePage=document.querySelector<HTMLElement>('.document-scroll .pdf-page')!,eraseBounds=erasePage.getBoundingClientRect(),eraseScale=eraseBounds.width/595;
 const capture=erasePage.setPointerCapture;erasePage.setPointerCapture=()=>{};
 const eraseEvent=(type:string,x:number)=>erasePage.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:8,pointerType:'mouse',button:type==='pointermove'?-1:0,buttons:['pointerup','pointercancel'].includes(type)?0:1,clientX:eraseBounds.left+x*eraseScale,clientY:eraseBounds.top+525*eraseScale}));
 eraseEvent('pointerdown',60);eraseEvent('pointermove',250);await until(()=>erasePage.dataset.erasingCount==='2','Dragging did not preview both crossed strokes');assert(!document.querySelector('.busy'),'Eraser blocked dragging with a busy operation');eraseEvent('pointerup',250);await idle();await click('Select');assert(document.querySelectorAll('.mark-hit').length===2,'Eraser did not remove exactly the two crossed pen strokes');
 await click('Eraser');eraseEvent('pointerdown',300);await until(()=>erasePage.dataset.erasingCount==='1','Click eraser preview missing');eraseEvent('pointercancel',300);await wait(200);await click('Select');assert(document.querySelectorAll('.mark-hit').length===2,'Cancelled erasing removed a stroke');
 erasePage.setPointerCapture=capture;await click('Undo');assert(document.querySelectorAll('.mark-hit').length===4,'One undo did not restore the entire eraser drag');for(let i=0;i<3;i++)await click('Undo');note('Held-button erasing catches rapid sweeps, supports cancellation and one-step undo');
 await click('Pen');await draw(100,500,300,500);await click('Eraser');
 const mode=document.querySelector<HTMLSelectElement>('select[aria-label="Eraser mode"]')!;assert(mode,'Eraser mode selector missing');mode.value='partial';mode.dispatchEvent(new Event('change',{bubbles:true}));await wait(200);await draw(200,460,200,540);await click('Select');assert(document.querySelectorAll('.mark-hit').length===2,'Partial eraser removed the entire stroke');
 await click('Eraser');const fullMode=document.querySelector<HTMLSelectElement>('select[aria-label="Eraser mode"]')!;fullMode.value='full';fullMode.dispatchEvent(new Event('change',{bubbles:true}));await wait(200);await draw(100,480,100,520);await click('Select');assert(document.querySelectorAll('.mark-hit').length===1,'Full eraser failed to remove the remaining stroke');for(let i=0;i<3;i++)await click('Undo');assert(document.querySelectorAll('.mark-hit').length===1,'Eraser mode undo sequence failed');note('Partial / Full selector preserves partial strokes and switches to whole-stroke removal');
 await click('Highlight');await draw(60,600,180,620);await click('Underline');await draw(60,650,180,670);await click('Select');
 const markupHit=(type:string)=>document.querySelector<HTMLButtonElement>(`.document-scroll .mark-hit[aria-label^="${type}:"]`);
 for(const [type,key] of [['Highlight','Delete'],['Underline','Backspace']]){
  const oldFocus=document.querySelector<HTMLTextAreaElement>('.properties textarea')!;oldFocus.focus();const hit=markupHit(type)!;assert(hit,`${type} not selectable`);
  if(type==='Highlight')hit.click();else{const b=hit.getBoundingClientRect();hit.setPointerCapture=()=>{};hit.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,pointerId:32,button:0,buttons:1,clientX:b.left+b.width/2,clientY:b.top+b.height/2}));await wait(100);hit.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,pointerId:32,button:0,buttons:0,clientX:b.left+b.width/2,clientY:b.top+b.height/2}));}
  await wait(200);assert(document.activeElement===hit,`${type} selection left focus in the text editor`);assert(document.querySelector('.annotation-delete'),`${type} has no visible delete button`);
  hit.dispatchEvent(new KeyboardEvent('keydown',{key,bubbles:true,cancelable:true}));await idle();assert(!markupHit(type),`${key} did not remove ${type}`);await click('Undo');assert(markupHit(type),`Undo did not restore ${type}`);
 }
 markupHit('Underline')!.click();await wait(200);document.querySelector<HTMLButtonElement>('.annotation-delete')!.click();await idle();assert(!markupHit('Underline'),'Visible delete button did not remove underline');await click('Undo');
 for(const value of ['full','partial']){await click('Eraser');const selector=document.querySelector<HTMLSelectElement>('select[aria-label="Eraser mode"]')!;selector.value=value;selector.dispatchEvent(new Event('change',{bubbles:true}));await wait(200);await draw(120,580,120,690);await click('Select');assert(!markupHit('Highlight')&&!markupHit('Underline'),`${value} eraser did not remove both markup types`);assert(document.querySelectorAll('.mark-hit').length===1,'Markup eraser removed an unrelated annotation');await click('Undo');assert(markupHit('Highlight')&&markupHit('Underline'),`${value} eraser undo did not restore the entire drag`);}
 await click('Undo');await click('Undo');assert(document.querySelectorAll('.mark-hit').length===1,'Markup deletion test cleanup failed');note('Highlight/underline selection, Delete/Backspace, visible delete button, both erasers and whole-gesture undo');
 await click('Note');const textarea=document.querySelector<HTMLTextAreaElement>('.properties textarea')!;text(textarea,'Browser QA 中文便箋');blur(textarea);await wait(200);await draw(350,200,380,230);assert(document.querySelector('.comments-list')?.textContent?.includes('中文便箋'),'Chinese note missing');note('Chinese note creation and comments panel');
 await click('Forms & Sign');const field=document.querySelector<HTMLInputElement>('.field input:not([type=checkbox]):not([type=radio])')!;text(field,'Browser QA form');blur(field);await idle();assert(document.querySelector<HTMLInputElement>('.field input:not([type=checkbox]):not([type=radio])')?.value==='Browser QA form','Form edit lost');note('Native PDF form editing');
 await click('Finish');await click('Watermark');await until(()=>!!document.querySelector('dialog'),'Watermark dialog missing');const inputs=document.querySelectorAll<HTMLInputElement>('dialog .dialog-body input');text(inputs[1],'CONFIDENTIAL');await wait(200);assert(document.querySelector('dialog .batch-preview')?.textContent==='CONFIDENTIAL','Batch preview missing');await click('Apply');await idle();note('Watermark preview and batch application');
 await click('Organize');await click('Duplicate');await idle();assert(document.querySelectorAll('.thumbnail-item').length===3,'Duplicate page missing');await click('Undo');await idle();assert(document.querySelectorAll('.thumbnail-item').length===2,'Duplicate undo failed');note('Page organization and undo');
 await click('Save a copy');await idle();await wait(300);await click('Save flattened copy');document.querySelector<HTMLButtonElement>('.dropdown button:last-child')!.click();await wait(200);await idle();await wait(300);assert(report.exports.length===2,'Both exports were not generated');assert(report.exports.every(e=>e.bytes>1000),'Empty PDF export');note('Editable and flattened PDF export through UI');
 await until(()=>document.querySelector('.document-title')?.textContent?.includes('Saved locally'),'Draft did not save');
 const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('local-pdf-studio');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const drafts=await new Promise<any[]>((resolve,reject)=>{const r=db.transaction('drafts').objectStore('drafts').getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});db.close();assert(drafts.some(d=>d.name==='QA sample.pdf'&&d.current.byteLength>1000),'Draft checkpoint missing');note('Real IndexedDB draft checkpoint');
 await click('Home');await until(()=>!!document.querySelector('.home'),'Home navigation failed');const draftButton=Array.from(document.querySelectorAll<HTMLButtonElement>('.draft-main')).find(b=>b.textContent?.includes('QA sample.pdf'));draftButton!.click();await until(()=>!!document.querySelector('.document-scroll'),'Draft did not restore');await idle();assert(document.querySelector('.comments-list')?.textContent?.includes('中文便箋'),'Restored draft lost annotations');note('Draft reopen restores annotated PDF');
 await click('Settings');const language=document.querySelector<HTMLSelectElement>('dialog select')!;language.value='zh';language.dispatchEvent(new Event('change',{bubbles:true}));await wait(300);assert(document.querySelector('dialog')?.textContent?.includes('自動 PDF 檢視器'),'Traditional Chinese labels missing');note('English / Traditional Chinese switching');
 const theme=document.querySelectorAll<HTMLSelectElement>('dialog select')[1];theme.value='dark';theme.dispatchEvent(new Event('change',{bubbles:true}));await wait(200);assert(document.documentElement.dataset.theme==='dark','Dark theme did not apply');note('Dark theme');theme.value='light';theme.dispatchEvent(new Event('change',{bubbles:true}));language.value='en';language.dispatchEvent(new Event('change',{bubbles:true}));await wait(200);await click('Done');
 await click('Home');await until(()=>!!document.querySelector('.home'),'Home navigation failed');
 const originalOpen=IDBFactory.prototype.open;
 try{
  IDBFactory.prototype.open=function(){throw new DOMException('Storage denied for QA','SecurityError');};
  const deniedInput=document.querySelector<HTMLInputElement>('input[type=file]')!;const deniedTransfer=new DataTransfer();deniedTransfer.items.add(new File([sample],'Storage failure QA.pdf',{type:'application/pdf'}));deniedInput.files=deniedTransfer.files;deniedInput.dispatchEvent(new Event('change',{bubbles:true}));
  await until(()=>!!document.querySelector('.document-scroll canvas')&&!document.querySelector('.page-error'),'Storage denial prevented opening');await idle();
  await until(()=>document.querySelector('.document-title')?.textContent?.includes('Save failed'),'Storage failure status missing');
  const count=report.exports.length;await click('Save a copy');await idle();await until(()=>report.exports.length>count,'Storage denial prevented emergency export');note('Storage denial leaves PDF usable and emergency export available');
 }finally{IDBFactory.prototype.open=originalOpen;}
 note('Browser integration suite complete');
}catch(e){report.failed.push(e instanceof Error?e.stack||e.message:String(e));}
report.finished=new Date().toISOString();(window as any).__pdfQA=report;await fetch('/__qa/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(report,null,2)});
