// Development-only end-to-end checks. Uses a synthetic local PDF and real
// IndexedDB transactions; concurrent saves represent independent tab writers.
import {getDraft,listDrafts,saveDraft,draftToken,deleteDraft,getPreferences,DraftConflictError} from '../src/storage';
const report:{suite:string;passed:string[];failed:string[];errors:string[];finished?:string}={suite:'Six improvements',passed:[],failed:[],errors:[]};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const assert=(value:unknown,message:string)=>{if(!value)throw Error(message);};
async function until(fn:()=>unknown,message:string,timeout=20000){const start=performance.now();while(!fn()){if(performance.now()-start>timeout)throw Error(message);await wait(100);}await wait(150);}
const idle=()=>until(()=>!document.querySelector('.busy'),'Operation did not finish');
const saved=()=>until(()=>document.querySelector('.document-title')?.textContent?.includes('Saved locally'),'Draft did not save');
async function click(label:string){const b=Array.from(document.querySelectorAll<HTMLButtonElement>('button')).find(b=>!b.disabled&&b.getClientRects().length&&(b.getAttribute('aria-label')===label||b.title===label||b.textContent?.trim()===label));assert(b,'Missing button: '+label);b!.click();await wait(200);}
const input=(el:HTMLInputElement|HTMLTextAreaElement,value:string)=>{Object.getOwnPropertyDescriptor(el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));};
const blur=(el:HTMLElement)=>el.dispatchEvent(new FocusEvent('focusout',{bubbles:true}));
function key(value:string,target:HTMLElement=document.body,extra:KeyboardEventInit={}){target.dispatchEvent(new KeyboardEvent('keydown',{key:value,bubbles:true,cancelable:true,...extra}));}
async function draw(x1:number,y1:number,x2:number,y2:number){const p=document.querySelector<HTMLElement>('.document-scroll .pdf-page')!,b=p.getBoundingClientRect(),z=b.width/595,old=p.setPointerCapture;p.setPointerCapture=()=>{};for(const [type,x,y] of [['pointerdown',x1,y1],['pointermove',x2,y2],['pointerup',x2,y2]] as const){p.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:9,button:type==='pointermove'?-1:0,buttons:type==='pointerup'?0:1,clientX:b.left+x*z,clientY:b.top+y*z}));await wait(60);}p.setPointerCapture=old;await idle();}
async function selectText(){await click('Select');(document.activeElement as HTMLElement)?.blur();const spans=document.querySelectorAll('.document-scroll .text-layer span'),r=document.createRange();r.setStart(spans[0].firstChild!,0);r.setEnd(spans[18].firstChild!,spans[18].textContent!.length);const s=window.getSelection()!;s.removeAllRanges();s.addRange(r);document.dispatchEvent(new Event('selectionchange'));await until(()=>!!document.querySelector('.selection-toolbar'),'Selection toolbar missing');}
const note=(text:string)=>report.passed.push(text);
window.addEventListener('error',e=>report.errors.push(e.message));window.addEventListener('unhandledrejection',e=>report.errors.push(String(e.reason)));
const originalDownload=HTMLAnchorElement.prototype.click;let exports=0;HTMLAnchorElement.prototype.click=function(){if(this.download&&this.href.startsWith('blob:'))exports++;else originalDownload.call(this);};
try{
 await until(()=>!!document.querySelector('.home'),'Home missing');const sample=await(await fetch('/test-artifacts/sample.pdf')).arrayBuffer(),transfer=new DataTransfer();transfer.items.add(new File([sample],'Improvements QA.pdf',{type:'application/pdf'}));const file=document.querySelector<HTMLInputElement>('input[type=file]')!;file.files=transfer.files;file.dispatchEvent(new Event('change',{bubbles:true}));await wait(1600);if(document.querySelector('dialog'))await click('Open original copy');await until(()=>document.querySelectorAll('.document-scroll .text-layer span').length>20,'PDF did not render');await idle();
 await click('Single page');input(document.querySelector<HTMLInputElement>('.page-controls input')!,'1');await wait(250);assert(document.querySelector<HTMLInputElement>('.page-controls input')?.value==='1','First page navigation failed');
 await click('Bookmarks');const bookmarkName=()=>document.querySelector<HTMLInputElement>('input[aria-label="Bookmark name"]')!;input(bookmarkName(),'Exam topic');await click('Add bookmark');await click('Next page');input(bookmarkName(),'Continue here');await click('Add bookmark');
 const rename=document.querySelector<HTMLInputElement>('.bookmark-row input')!;input(rename,'Exam chapter');blur(rename);await wait(200);
 await click('Organize');await click('Pages');await click('Move up');await idle();await click('Bookmarks');assert(document.querySelector('.bookmark-row button')?.textContent==='Page 2','Bookmark did not follow reordered page');await click('Undo');assert(document.querySelector('.bookmark-row button')?.textContent==='Page 1','Bookmark did not follow undo');
 await click('Remove bookmark: Continue here');document.querySelector<HTMLButtonElement>('.bookmark-row button')!.click();await wait(300);await saved();note('Named bookmarks add, rename, remove and follow page reordering and undo');
 await click('Annotate');await click('Pen');await draw(100,500,300,500);await click('Eraser');const size=document.querySelector<HTMLInputElement>('input[aria-label="Eraser size"]')!;input(size,'40');await wait(200);assert((await getPreferences()).eraserSize===40,'Eraser size was not remembered');const mode=document.querySelector<HTMLSelectElement>('select[aria-label="Eraser mode"]')!;mode.value='partial';mode.dispatchEvent(new Event('change',{bubbles:true}));await wait(200);const cursorPage=document.querySelector<HTMLElement>('.document-scroll .pdf-page')!,cursorBox=cursorPage.getBoundingClientRect();cursorPage.dispatchEvent(new PointerEvent('pointermove',{bubbles:true,button:-1,buttons:0,clientX:cursorBox.left+200,clientY:cursorBox.top+450}));await wait(150);assert(document.querySelector<HTMLElement>('.eraser-cursor')?.style.width==='40px','Cursor does not match eraser size');await draw(200,460,200,540);await click('Select');assert(document.querySelectorAll('.mark-hit').length===1,'Partial eraser lost remaining ink');await click('Undo');await click('Undo');await click('Eraser');input(document.querySelector('input[aria-label="Eraser size"]')!,'20');await wait(200);note('Eraser sizing updates the cursor, clips ink and persists its setting');
 (document.activeElement as HTMLElement)?.blur();key('h');await wait(200);assert(document.querySelector('.document-scroll .tool-Highlight'),'H shortcut failed');const textBox=document.querySelector<HTMLTextAreaElement>('.properties textarea')!;textBox.focus();key('p',textBox);await wait(150);assert(document.querySelector('.tool-Highlight'),'Typing switched tools');textBox.blur();key('p',document.body,{isComposing:true});key('p',document.body,{ctrlKey:true});await wait(150);assert(document.querySelector('.tool-Highlight'),'Composition/modifier switched tools');key('l');await wait(150);assert(document.querySelector('.laser-overlay'),'L shortcut failed');key('v');await wait(150);note('Tool shortcuts work and ignore typing, composition and modified keys');
 await selectText();document.querySelector<HTMLButtonElement>('.selection-toolbar button[aria-label="Highlight"]')!.click();await idle();assert(document.querySelector('.mark-hit[aria-label^="Highlight:"]'),'Selection toolbar did not create highlight');await click('Undo');
 await selectText();document.querySelector<HTMLButtonElement>('.selection-toolbar button[aria-label="Note"]')!.click();await wait(200);input(document.querySelector<HTMLTextAreaElement>('.selection-toolbar textarea')!,'Study note 中文');await click('Add note');await idle();assert(document.querySelector('.comments-list')?.textContent?.includes('Study note 中文'),'Selection note missing');await click('Undo');note('Selected text toolbar creates editable highlights and composed notes');
 const originalFetch=window.fetch;try{window.fetch=async(input,init)=>String(input).includes('manifest.json')?new Response(JSON.stringify({version:'99.0.0'}),{headers:{'content-type':'application/json'}}):originalFetch(input,init);window.dispatchEvent(new Event('focus'));await until(()=>!!document.querySelector('.version-notice'),'New version was not detected');assert(document.querySelector('.version-badge')?.textContent==='v1.2.3','Running version incorrect');assert(!document.querySelector<HTMLButtonElement>('.version-notice button')?.disabled,'Refresh button is unexpectedly disabled');}finally{window.fetch=originalFetch;}window.dispatchEvent(new Event('focus'));await until(()=>!document.querySelector('.version-notice'),'Update notice did not reset');note('Running version and update detection work without automatic page reload');
 await saved();const activeSummary=(await listDrafts()).find(d=>d.name==='Improvements QA.pdf')!,active=(await getDraft(activeSummary.id))!;
 const race={...active,id:'qa-race-'+crypto.randomUUID(),name:'Race fixture.pdf'};const token=await saveDraft(race,null);const raced=await Promise.allSettled([saveDraft({...race,page:0},token),saveDraft({...race,page:1},token)]);assert(raced.filter(r=>r.status==='fulfilled').length===1,'Concurrent writers both saved');assert(raced.some(r=>r.status==='rejected'&&r.reason instanceof DraftConflictError),'Concurrent save did not report conflict');await deleteDraft(race.id);
 await new Promise<void>((resolve,reject)=>{const old=indexedDB.open('local-pdf-studio',2);old.onerror=()=>old.error?.name==='VersionError'?resolve():reject(old.error);old.onsuccess=()=>{old.result.close();reject(Error('Old unguarded storage version still opens'));};});note('Real IndexedDB rejects concurrent stale writes and older unguarded clients');
 await saveDraft({...active,bookmarks:[...(active.bookmarks||[]),{id:'other-tab',pageId:active.bookmarks![0].pageId,label:'Other tab bookmark'}]},draftToken(active));
 await click('Bookmarks');input(bookmarkName(),'This tab bookmark');await click('Add bookmark');await until(()=>!!document.querySelector('.draft-conflict'),'Draft conflict warning missing');assert((await getDraft(active.id))!.bookmarks?.some(b=>b.id==='other-tab'),'Conflicting write overwrote the other tab');const exportCount=exports;await click('Export PDF');await idle();assert(exports===exportCount+1,'Conflict prevented PDF export');await click('Save separate draft');await until(()=>!document.querySelector('.draft-conflict'),'Separate draft did not resolve conflict');await saved();
 const separated=(await listDrafts()).find(d=>d.name==='Improvements QA - Separate draft.pdf')!,copy=(await getDraft(separated.id))!;assert(copy.id!==active.id,'Separate draft reused conflicting ID');assert(copy.bookmarks?.some(b=>b.label==='This tab bookmark')&&!copy.bookmarks?.some(b=>b.id==='other-tab'),'Separate draft lost this tab state');assert((await getDraft(active.id))!.bookmarks?.some(b=>b.id==='other-tab'),'Separate draft altered original');note('Conflict UI preserves both versions, exports, and saves a separate draft with local bookmarks');
 await click('Home');await until(()=>!!document.querySelector('.home'),'Home missing');const reopen=Array.from(document.querySelectorAll<HTMLButtonElement>('.draft-main')).find(b=>b.textContent?.includes('Improvements QA - Separate draft.pdf'))!;reopen.click();await until(()=>!!document.querySelector('.document-scroll'),'Separate draft did not reopen');await click('Bookmarks');assert(Array.from(document.querySelectorAll<HTMLInputElement>('.bookmark-row input')).some(i=>i.value==='This tab bookmark'),'Reopened draft lost bookmarks');await saved();note('Separate draft and personal bookmarks recover after reopening');
}catch(e){report.failed.push(e instanceof Error?e.stack||e.message:String(e));}
finally{HTMLAnchorElement.prototype.click=originalDownload;}
report.finished=new Date().toISOString();await fetch('/__qa/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(report,null,2)});
