import {getDraft,listDrafts} from '../src/storage';
import {EngineClient} from '../src/client';
// Development-only browser integration runner. Not included in the extension build.
const report:{passed:string[];failed:string[];errors:string[];exports:{name:string;bytes:number}[];finished?:string}={passed:[],failed:[],errors:[],exports:[]};
const wait=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function until(fn:()=>any,message:string,timeout=20000){const start=performance.now();while(!fn()){if(performance.now()-start>timeout)throw new Error(message);await wait(100);}await wait(150);}
const assert=(value:any,message:string)=>{if(!value)throw new Error(message);};
const buttons=(label:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('button')).filter(b=>b.getAttribute('aria-label')===label||b.title===label||b.textContent?.trim()===label);
async function click(label:string){const b=buttons(label).find(b=>b.getClientRects().length&&!b.disabled);assert(b,`Button missing: ${label}`);b!.click();await wait(200);}
const text=(el:HTMLInputElement|HTMLTextAreaElement,value:string)=>{Object.getOwnPropertyDescriptor(el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')!.set!.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));};
const blur=(el:HTMLElement)=>{el.dispatchEvent(new FocusEvent('focusout',{bubbles:true}));};
const idle=()=>until(()=>!document.querySelector('.busy'),'Busy operation did not finish');
const note=(name:string)=>report.passed.push(name);
window.addEventListener('error',e=>report.errors.push(e.message));window.addEventListener('unhandledrejection',e=>report.errors.push(String(e.reason)));
const captured:Promise<ArrayBuffer>[]=[];
const anchorClick=HTMLAnchorElement.prototype.click;
HTMLAnchorElement.prototype.click=function(){if(this.download&&this.href.startsWith('blob:')){captured.push(fetch(this.href).then(r=>r.arrayBuffer()));fetch(this.href).then(r=>r.arrayBuffer()).then(b=>report.exports.push({name:this.download,bytes:b.byteLength}));}else anchorClick.call(this);};
async function draw(x1:number,y1:number,x2:number,y2:number){const page=document.querySelector<HTMLElement>('.document-scroll .pdf-page')!;const rect=page.getBoundingClientRect(),scale=rect.width/595;const capture=page.setPointerCapture;page.setPointerCapture=()=>{};const fire=(type:string,x:number,y:number)=>page.dispatchEvent(new PointerEvent(type,{bubbles:true,pointerId:1,pointerType:'mouse',button:0,buttons:type==='pointerup'?0:1,clientX:rect.left+x*scale,clientY:rect.top+y*scale,pressure:.5}));fire('pointerdown',x1,y1);await wait(60);fire('pointermove',x2,y2);await wait(60);fire('pointerup',x2,y2);page.setPointerCapture=capture;await idle();}


async function moveHandle(target:HTMLElement,dx:number,dy:number){const b=target.getBoundingClientRect(),start=[b.left+b.width/2,b.top+b.height/2],capture=target.setPointerCapture;target.setPointerCapture=()=>{};for(const [type,x,y] of [['pointerdown',...start],['pointermove',start[0]+dx,start[1]+dy],['pointerup',start[0]+dx,start[1]+dy]] as const){target.dispatchEvent(new PointerEvent(String(type),{bubbles:true,pointerId:8,button:type==='pointermove'?-1:0,buttons:type==='pointerup'?0:1,clientX:Number(x),clientY:Number(y)}));await wait(70);}target.setPointerCapture=capture;await idle();}
try{
 await until(()=>document.querySelector('.home'),'Home did not render');
 const sample=await (await fetch('/test-artifacts/sample.pdf')).arrayBuffer(),transfer=new DataTransfer();const filename='Text box QA '+crypto.randomUUID()+'.pdf';transfer.items.add(new File([sample],filename,{type:'application/pdf'}));const input=document.querySelector<HTMLInputElement>('input[type=file]')!;input.files=transfer.files;input.dispatchEvent(new Event('change',{bubbles:true}));await wait(1500);if(buttons('Open original copy').length)await click('Open original copy');await until(()=>document.querySelectorAll('.document-scroll .text-layer span').length>20,'No PDF');await click('Single page');await click('Annotate');await click('Text');await draw(80,250,350,260);await idle();await wait(150);
 const field=()=>document.querySelector<HTMLTextAreaElement>('.text-box-editor')||document.querySelector<HTMLTextAreaElement>('.properties textarea')!;assert(document.activeElement===field(),'Placing a box did not focus text entry');assert(field().selectionStart===0&&field().selectionEnd===field().value.length,'Placeholder not selected');note('New text boxes support typing directly on the PDF and select placeholder text');
 text(field(),'Typed text 中文 before save');field().dispatchEvent(new KeyboardEvent('keydown',{key:'s',ctrlKey:true,bubbles:true,cancelable:true}));await until(()=>captured.length>0,'No export');const e=new EngineClient();try{const info=await e.call('open',{bytes:new Uint8Array(await captured[0])});const mark=info.pages.flatMap(p=>p.marks).find(a=>a.type==='FreeText')!;assert(mark.contents==='Typed text 中文 before save','Ctrl+S exported stale text: '+mark.contents);assert(mark.rect[3]-mark.rect[1]>=27,'Short text box remained unreadable');note('Ctrl+S includes focused text, preserves Chinese and creates a readable minimum box');}finally{e.close();}
 await idle();field().focus();text(field(),'Line one 中文\nLine two\nLine three');await until(()=>document.querySelector('.document-title')?.textContent?.includes('Saved locally'),'Typing did not autosave');await wait(200);
 assert(document.activeElement===field(),'Autosave stole typing focus');const draft=(await listDrafts()).find(d=>d.name===filename)!;const full=(await getDraft(draft.id))!;const verify=new EngineClient();try{const inf=await verify.call('open',{bytes:new Uint8Array(full.current)});assert(inf.pages[0].marks.some(a=>a.contents==='Line one 中文\nLine two\nLine three'),'Autosave omitted unblurred input');}finally{verify.close();}
 assert(document.querySelector('.properties')?.textContent?.includes('Some text does not fit'),'Clipped text was not explained');note('Multiline text autosaves without blur or focus loss; overflow is reported');
 field().blur();await idle();const hit=document.querySelector<HTMLElement>('.document-scroll .mark-hit')!,initial=hit.getBoundingClientRect();await moveHandle(document.querySelector<HTMLElement>('.text-box-move')!,30,20);await wait(150);const moved=document.querySelector<HTMLElement>('.document-scroll .mark-hit')!.getBoundingClientRect();assert(Math.abs(moved.left-initial.left-30)<2&&Math.abs(moved.top-initial.top-20)<2,'Moving text box failed');
 const handle=document.querySelector<HTMLElement>('.document-scroll .resize-handle')!;await moveHandle(handle,0,110);await wait(200);assert(!document.querySelector('.properties')?.textContent?.includes('Some text does not fit'),'Resizing did not reveal text');note('Text boxes move and resize; expanding the box reveals clipped lines');
 document.querySelector<HTMLElement>('.document-scroll .mark-hit')!.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));await wait(150);assert(document.activeElement===field()&&field().classList.contains('text-box-editor'),'Double click did not open inline text editing');text(field(),'Changed again');field().blur();await idle();await click('Undo');await wait(200);document.querySelector<HTMLButtonElement>('.document-scroll .mark-hit')!.click();await wait(100);assert(field().value==='Line one 中文\nLine two\nLine three','Undo did not restore text');await click('Redo');document.querySelector<HTMLButtonElement>('.document-scroll .mark-hit')!.click();await wait(100);assert(field().value==='Changed again','Redo did not restore text');note('Double click reopens text entry; undo and redo restore text correctly');
 await click('Save a copy');await idle();await until(()=>captured.length===2,'Second export missing');const final=new EngineClient();try{const inf=await final.call('open',{bytes:new Uint8Array(await captured[1])});assert(inf.pages[0].marks.find(a=>a.type==='FreeText')?.contents==='Changed again','Reopened PDF lost edits');}finally{final.close();}note('Moved/resized edited text survives export and reopening');
}catch(e){report.failed.push(e instanceof Error?e.stack||e.message:String(e));}
finally{HTMLAnchorElement.prototype.click=anchorClick;}
report.finished=new Date().toISOString();await fetch('/__qa/result',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(report,null,2)});
