import type {Mark,Point} from './types';
export type AnnotationFilter={type:string;color:string};
export const allAnnotations:AnnotationFilter={type:'all',color:'all'};
export function annotationColor(c:number[]){const rgb=c.length===4?[0,1,2].map(i=>1-Math.min(1,c[i]+c[3])):c.length===3?c:[c[0]??0,c[0]??0,c[0]??0];return '#'+rgb.map(v=>Math.round(Math.max(0,Math.min(1,v))*255).toString(16).padStart(2,'0')).join('');}
export function matchesAnnotation(a:Pick<Mark,'type'|'color'>,f:AnnotationFilter){return (f.type==='all'||a.type===f.type)&&(f.color==='all'||annotationColor(a.color)===f.color);}
export function inQuad(p:Point,q:number[]){const points=[[q[0],q[1]],[q[2],q[3]],[q[6],q[7]],[q[4],q[5]]];const cross=points.map((a,i)=>{const b=points[(i+1)%4];return (b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0]);});return cross.some(v=>Math.abs(v)>.001)&&(cross.every(v=>v>=-.001)||cross.every(v=>v<=.001));}
export type StudyNote={id:string;page:number;type:string;color:number[];text:string;contents:string};
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function studyHTML(name:string,notes:StudyNote[],t:(s:string)=>string){return '<!doctype html><html lang="'+(t('Page')==='Page'?'en':'zh-Hant')+'"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(name)+' — '+escape(t('Study notes'))+'</title><style>body{font:16px/1.6 system-ui,sans-serif;max-width:850px;margin:40px auto;padding:0 24px;color:#172b4d}article{break-inside:avoid;border-left:5px solid var(--color);padding:4px 20px;margin:24px 0}h2{font-size:16px}p,blockquote{white-space:pre-wrap;overflow-wrap:anywhere}blockquote{margin:12px 0}small{color:#475569}</style><h1>'+escape(name)+'</h1><p>'+escape(t('Study notes'))+' · '+notes.length+'</p>'+notes.map(n=>'<article style="--color:'+annotationColor(n.color)+'"><h2>'+escape(t('Page'))+' '+(n.page+1)+' · '+escape(t(n.type==='Text'?'Note':n.type))+'</h2>'+(n.text?'<blockquote>'+escape(n.text)+'</blockquote>':'')+(n.contents?'<p>'+escape(n.contents)+'</p>':'')+(!n.text&&!n.contents?'<small>'+escape(t('No extractable text in this annotation.'))+'</small>':'')+'</article>').join('')+'</html>';}
