import {useRef,useState} from 'react';
import {Trash2,Upload,PenLine,Type} from 'lucide-react';
import {Modal,Button} from './ui';
import type {Preferences} from './types';
import type {Translate} from './i18n';
export function SignatureDialog({t,preferences,onPreferences,onClose,onUse}:{t:Translate;preferences:Preferences;onPreferences:(p:Preferences)=>void;onClose:()=>void;onUse:(bytes:Uint8Array)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),file=useRef<HTMLInputElement>(null);const [mode,setMode]=useState('Draw'),[typed,setTyped]=useState(''),[uploaded,setUploaded]=useState(''),[remember,setRemember]=useState(false),[name,setName]=useState(''),[hasInk,setHasInk]=useState(false);const drawing=useRef(false);
 const use=async(data?:string)=>{let url=data;if(!url&&mode==='Draw')url=canvas.current!.toDataURL('image/png');if(!url&&mode==='Upload')url=uploaded;if(!url&&mode==='Type'){const c=document.createElement('canvas');c.width=1000;c.height=220;const ctx=c.getContext('2d')!;ctx.fillStyle='#172b4d';ctx.font='italic 64px "Segoe UI", "Microsoft JhengHei", sans-serif';ctx.fillText(typed,24,130,950);url=c.toDataURL('image/png');}if(!url)return;if(remember&&!data)onPreferences({...preferences,signatures:[...preferences.signatures,{name:name||t('Your signature'),data:url}]});onUse(new Uint8Array(await (await fetch(url)).arrayBuffer()));onClose();};
 return <Modal t={t} title={t('Signature')} onClose={onClose} wide><div className="dialog-body">
  <div className="segmented">{[[PenLine,'Draw'],[Type,'Type'],[Upload,'Upload']].map(([icon,label])=><Button key={String(label)} icon={icon} label={t(String(label))} active={mode===label} onClick={()=>setMode(String(label))}/>)}</div>
  {mode==='Draw'&&<><canvas className="signature-pad" ref={canvas} width={1000} height={280} onPointerDown={e=>{drawing.current=true;const c=canvas.current!,b=c.getBoundingClientRect(),ctx=c.getContext('2d')!;ctx.beginPath();ctx.moveTo((e.clientX-b.left)*1000/b.width,(e.clientY-b.top)*280/b.height);e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drawing.current)return;const c=canvas.current!,b=c.getBoundingClientRect(),ctx=c.getContext('2d')!;ctx.lineWidth=2+(e.pressure||.5)*3;ctx.lineCap='round';ctx.strokeStyle='#172b4d';ctx.lineTo((e.clientX-b.left)*1000/b.width,(e.clientY-b.top)*280/b.height);ctx.stroke();setHasInk(true);}} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/><button className="text-button" onClick={()=>{canvas.current!.getContext('2d')!.clearRect(0,0,1000,280);setHasInk(false);}}>{t('Clear')}</button></>}
  {mode==='Type'&&<input autoFocus className="typed-signature" aria-label={t('Your signature')} placeholder={t('Your signature')} value={typed} onChange={e=>setTyped(e.target.value)}/>}
  {mode==='Upload'&&<div className="signature-upload"><Button icon={Upload} label={t('Choose PNG or JPEG')} onClick={()=>file.current?.click()}/>{uploaded&&<img src={uploaded}/>}<input hidden type="file" ref={file} accept="image/png,image/jpeg" onChange={e=>{const f=e.target.files?.[0];if(f){const r=new FileReader();r.onload=()=>setUploaded(String(r.result));r.readAsDataURL(f);}}}/></div>}
  <label className="check-row"><input type="checkbox" checked={remember} onChange={e=>setRemember(e.target.checked)}/>{t('Remember this signature')}</label>{remember&&<input value={name} aria-label={t('Signature name')} placeholder={t('Signature name')} onChange={e=>setName(e.target.value)}/>}
  {!!preferences.signatures.length&&<><h3>{t('Saved signatures')}</h3><div className="saved-signatures">{preferences.signatures.map((s,i)=><div key={i}><button onClick={()=>use(s.data)} title={s.name}><img src={s.data}/><span>{s.name}</span></button><Button icon={Trash2} compact label={t('Remove saved signature')} onClick={()=>onPreferences({...preferences,signatures:preferences.signatures.filter((_,n)=>n!==i)})}/></div>)}</div></>}
 </div><div className="dialog-actions"><button onClick={onClose}>{t('Cancel')}</button><button className="primary" disabled={mode==='Draw'?!hasInk:mode==='Type'?!typed.trim():!uploaded} onClick={()=>use()}>{t('Use signature')}</button></div></Modal>;
}
